# Generated by Django 2.2.3 on 2019-07-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_auto_20190723_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='placa',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
