# Generated by Django 2.2.3 on 2019-07-24 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0005_auto_20190724_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='horario',
            field=models.DateTimeField(default='24/07/2019 - 12:49:25'),
        ),
    ]
