# Generated by Django 2.2.3 on 2019-07-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0006_auto_20190724_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='horario',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
