# Generated by Django 2.2.3 on 2019-07-24 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0011_auto_20190724_2201'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='valorestacionamento',
            table=None,
        ),
    ]
