# Generated by Django 2.2.3 on 2019-07-24 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0012_auto_20190724_2211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='valorestacionamento',
            old_name='valorFDS',
            new_name='periodoFDS',
        ),
        migrations.RenameField(
            model_name='valorestacionamento',
            old_name='valorFDS_currency',
            new_name='periodoFDS_currency',
        ),
        migrations.RenameField(
            model_name='valorestacionamento',
            old_name='valorManha',
            new_name='periodoManha',
        ),
        migrations.RenameField(
            model_name='valorestacionamento',
            old_name='valorManha_currency',
            new_name='periodoManha_currency',
        ),
        migrations.RenameField(
            model_name='valorestacionamento',
            old_name='valorTarde',
            new_name='periodoTarde',
        ),
        migrations.RenameField(
            model_name='valorestacionamento',
            old_name='valorTarde_currency',
            new_name='periodoTarde_currency',
        ),
    ]
