# Generated by Django 2.2.3 on 2019-07-25 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0014_veiculo_exited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculo',
            name='exited',
        ),
    ]
