# Generated by Django 2.2.3 on 2019-07-26 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0015_remove_veiculo_exited'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='ja_saiu',
            field=models.BooleanField(default=False),
        ),
    ]
