# Generated by Django 2.2.3 on 2019-07-26 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0016_veiculo_ja_saiu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculo',
            name='ja_saiu',
        ),
    ]
