# Generated by Django 2.2.3 on 2019-07-26 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0017_remove_veiculo_ja_saiu'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ValorEstacionamento',
            new_name='Valor',
        ),
    ]
