# Generated by Django 2.2.3 on 2019-07-26 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0021_veiculo_ativo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Horario',
            new_name='Data',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='horario_entrada',
            new_name='data_entrada',
        ),
        migrations.RenameField(
            model_name='veiculo',
            old_name='horario',
            new_name='data_entrada',
        ),
    ]
