# Generated by Django 2.2.3 on 2019-07-26 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0022_auto_20190726_1001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro',
            old_name='horario_saida',
            new_name='data_saida',
        ),
    ]
