# Generated by Django 2.2.3 on 2019-07-26 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0024_auto_20190726_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='veiculo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sistema.Veiculo'),
            preserve_default=False,
        ),
    ]
