# Generated by Django 2.2.3 on 2019-07-26 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0025_registro_veiculo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataEntrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateTimeField(auto_now_add=True, verbose_name='data_entrada')),
            ],
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='ativo'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='cor',
            field=models.CharField(max_length=50, verbose_name='cor'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='data_entrada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.DataEntrada'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='marca',
            field=models.CharField(max_length=100, verbose_name='marca'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='modelo',
            field=models.CharField(max_length=100, verbose_name='modelo'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='placa',
            field=models.CharField(max_length=8, verbose_name='placa'),
        ),
        migrations.DeleteModel(
            name='Data',
        ),
    ]
