# Generated by Django 2.2.3 on 2019-07-26 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0027_auto_20190726_1032'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataSaida',
        ),
    ]
